name: Deploy to Server

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Step 2: Set up .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Publish Blazor App
      run: dotnet publish -c Release -o output

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to Server
      env:
        SSH_AUTH_SOCK: ${{ secrets.SSH_KEY }}
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" output/ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/var/www/portfolio

